= Лабораторная работа № 1: Исполняемые фалы

== Настройка
=== GitHub

Результаты домашних работ должны быть представлены на GitHub, для чего у тебя должена быть там учётка. Свой код надо хранить *строго* в приватных репозиториях.

=== Vagrant

Для выполнения заданий потребуется использовать готовый преконфигурированный Vagrant-образ виртуальной машины, который содержит все необходимые инструменты для запуска, тестирования и отладки кода. http://www.vagrantup.com/downloads.html[Vagrant] — это средство управления виртуальными машинами, он будет использоваться для загрузки и запуска подготовленного образа виртуальной машины.

. Vagrant зависит от VirtualBox (программное обеспечение с открытым программным кодом для виртуализации), поэтому прежде всего необходимо загрузить и установить свежую версию https://www.virtualbox.org/wiki/Downloads[с сайта VirtualBox].
. Установить свежую версию http://www.vagrantup.com/downloads.html[с сайта Vagrant].
. После установки Vagrant нужно ввести в терминал следующие комманды:
+
----
$ mkdir cs162-vm
$ cd cs162-vm
$ vagrant init cs162/spring2019
$ vagrant up
$ vagrant ssh
---- 
+
Эти команды приведут к тому, что произойдет загрузка подготовленного образа виртуальной машины, она будет запущена и будет поднято ssh-соединение с хоста в виртуальную машину. Отметим, что команда «up» требует для выполнения достаточно много времени и устойчивое соединение с интернетом.

. Все vagrant-команды требуется запускать из директория `cs162-vm`, который был создан ранее. *Нельзя удалять этот директорий*, иначе vagrant не будет знать как управлять виртуальной машиной (ВМ), которая была создана.
. Команда `vagrant halt` приведёт к остановке виртуальной машины. Для следующего запуска ВМ достаточно ввести только две комманды:
+
----
vagrant up
vagrant ssh
----