= Лабораторная работа № 1: Исполняемые фалы

== Настройка
=== GitHub

Результаты домашних работ должны быть представлены на GitHub, для чего у тебя должена быть там учётка. Свой код надо хранить *строго* в приватных репозиториях.

=== Vagrant

Для выполнения заданий потребуется использовать готовый преконфигурированный Vagrant-образ виртуальной машины, который содержит все необходимые инструменты для запуска, тестирования и отладки кода. http://www.vagrantup.com/downloads.html[Vagrant] — это средство управления виртуальными машинами, он будет использоваться для загрузки и запуска подготовленного образа виртуальной машины.

[NOTE]
.*Только для пользователей Windows*
--
Поскольку Windows не поддерживает `ssh`, комманда `vagrant ssh`, которая потребуется вдальнейшем, приведет к ошибке. Vagrant предложит скачать Cygwin или что-то похожее, что поддерживает `ssh`. Cygwin — это набор программ (Linux комманд) для Windows. Тебе необходимо поставить Cygwin и использовать его терминал для выполнения команд. 

. Скачать с http://cygwin.com/install.html[сайта Cygwin] дистрибутив, подходящий к установленной версии Windows.
. Запустить скачаный файл (`setupx84_64.exe` или типа того).
. На экране приветствия нажать «Далее».
. На экране «Choose A Download Source» выбрать «Install from Internet» и нажать «Далее».
. На экране «Select Root Install Directory» нужно оставить предложенное значение для «Root Directory» и выбрать установку для всех пользователей «All Users». Нажать «Далее».
. На экране «Select Local Package Directory» ничего не трогать. Нажать «Далее».
. На экране «Select Your Internet Connection» выбрать «Direct Connection». Нажать «Далее».
. (Действие не требуется) Cygwin загрузит список доступных зеркал (то есть серверов на которых хранится программное обеспечение Cygwin).
. На экране «Choose A Download Site» нужно выбрать какой-нибудь сайт и нажать «Далее».
. (Действие не требуется) Cygwin загрузит список доступного программного обеспечения.
. Теперь ты попал на экран «Select Packages». Выбери из выпадающего списка «View» в верхнем левом углу «Full» вместо «Category». Больше ничего не трогать.
. Для каждого перечисленных ниже пакетов нажми на надпись «Skip», чтоб выбрать этот пакет для установки. Поиск пакета удобно осуществлять с помощью строки поиска «Search». При нажатии на «Skip» надпись должна превращаться в номер версии пакета, типа `2.1.4-1`. Возможно некоторые пакеты уже будут выбраны для установки, тогда нажимать ничего не надо.
+
[cols="1,3"]
|===
|Пакет | Описание
|bash | THE GNU Bourne Again SHell
|git | Distributed version control system
|openssh| The OpenSSH server and client programs|
|===
. Нажми «Далее» для проверки списка установки.
. На экране «Resolving Dependencies» удостоверься, что выбран пункт «Select required packages» и нажми «Далее».
. (Действие не требуется) Cygwin установит все выбранные пакеты.
. На экране «Create Icons» лучше выбрать оба пункта «Desktop icons» и «Start Menu icons», чтобы было легче отыскать «Cygwin Terminal». Нажми «Finish» для завершения.

Все последующие команды следует вводить в терминале «Cygwin Terminal».

--
. Vagrant зависит от VirtualBox (программное обеспечение с открытым программным кодом для виртуализации), поэтому прежде всего необходимо загрузить и установить свежую версию с https://www.virtualbox.org/wiki/Downloads[сайта VirtualBox].
. Установить свежую версию с http://www.vagrantup.com/downloads.html[сайта Vagrant].
. После установки Vagrant нужно ввести в терминал следующие комманды:
+
----
$ mkdir cs162-vm
$ cd cs162-vm
$ vagrant init cs162/spring2019
$ vagrant up
$ vagrant ssh
---- 
+
Эти команды приведут к тому, что произойдет загрузка подготовленного образа виртуальной машины, она будет запущена и будет поднято ssh-соединение с хоста в виртуальную машину. Отметим, что команда «up» требует для выполнения достаточно много времени и устойчивое соединение с интернетом.

. Все vagrant-команды требуется запускать из директория `cs162-vm`, который был создан ранее. *Нельзя удалять этот директорий*, иначе vagrant не будет знать как управлять виртуальной машиной (ВМ), которая была создана.
. Команда `vagrant halt` приведёт к остановке виртуальной машины. Для следующего запуска ВМ достаточно ввести только две комманды:
+
----
vagrant up
vagrant ssh
----

==== Решение проблем с Vagrant

Если комманда `vagrant up` выпадает с ошибкой, попробуй выполнить `vagrant provision` и проверить не исправит ли она ошибку. Если совсем всё плохо, можно попробовать полностью удалить ВМ командой `vagrant destroy`. Потом снова создать ВМ `vagrant up`.

==== Имя пользователя Git и емейл

Выполни эти команды чтобы настроить имя пользователя и емейл, которые будут использоваться в git-коммитах. Не забудь заменить `ТВОЁ_ИМЯ` и `ТВОЯ_ПОЧТА_КОМ` на нормальное имя (лучше латиницей) и на нормальную почту.
----
$ git config --global user.name "ТВОЁ_ИМЯ"
$ git config --global user.email "ТВОЯ_ПОЧТА_КОМ"
----

==== ssh-ключи

Для того, чтобы можно было изнутри ВМ работать с GitHub нужно настроить ssh-ключи.

В терминале ВМ нуно выполнить:
----

$ ssh-keygen -N "" -f ~/.ssh/id_rsa
$ cat ~/.ssh/id_rsa.pub
----

Первая команда создает новую пару ssh-ключей. Вторая команда выводит на экран публичный ключ. Для доступа к GitHub по ключам нужно перейти по ссылке https://github.com/settings/keys и добавить показанный на экране публичный ключ к GitHub-аккаунту. Можно назвать этот ключ произвольным образом, но лучше, чтобы название что-то обозначало, например, «OS_VM». Ключ должен начинаться с «ssh-rsa» и заканчиваться «vagrant@development».

==== Репозитории

При выдаче любого задания, включая это, будет предоставлена ссылка, ведущая на GitHub Classroom (надстрока над GitHub для ведения занятий). После перехода по этой ссылке системой будет предложено принять задание, нажав кнопку «Accept this assignment». При этом на GitHub будет создан индивидуальный репозиторий с начальными файлами задания, которые надо будет дополнить. Например, для этого задания будет создан индивидуальный репозиторий с адресом  `https://github.com/uniyar-os/hw-01-твой_github_юзернейм`. Этот репозиторий будет приватным — данные находящиеся в нём будут доступны только студенту и преподавателю.

Теперь следует:  Для этого в терминале ВМ:

. Cделать копию репозитория (клон) в ВМ.
+
----
$ git clone git@github.com:uniyar-os/hw-01-твой_github_юзернейм.git
----
+
. Удостовериться, что в текущем директории внутри ВМ появилась папка `hw-01-твой_github_юзернейм`. 
+
----
$ ls
----
+
Именно в в папку `hw-01-твой_github_юзернейм` «склонирован» удаленный репозиторий, и именно в ней следует работать с файлами, регулярно фиксируя изменения в файлах (`git commit`) и отправляя (`git push`) эти изменения в удаленный репозиторий.
+
. Перейди в папку `hw-01-твой_github_юзернейм` командой:
+
----
$ cd w-01-твой_github_юзернейм
----

=== Редактирование файлов в ВМ

В образ ВМ добавлена поддержка удаленного доступа к файлам (SMB-сервер), которая позволяет редактировать файлы внутри папки ВМ пользователя `vagrant` (именно в нее ты склонировал репозиторий). То есть можно доступиться до папки ВМ с помощью текстовых редакторов установленных на хостовой системе. *Это рекомендуемый способ работы с файлами в этом курсе.* Есть и другие, менее удобные способы. Например использовать текстовые редакторы (`nano`, `vim`) непосредственно в терминале.

==== Windows

. Открой проводник, нажми Ctrl+L для фокусировки на элементе ввода расположения.
. Напечатай `\\192.168.162.162\vagrant` и нажми `Enter`.
. Имя пользователя `vagrant`, пароль `vagrant`.

Тебе должно быть видно содержимое директория пользователя `vagrant`, в том числе и `hw-01-твой_github_юзернейм`.

==== Mac OS X

. Открой Finder.
. В меню выбери «Переход → Подключение к серверу...»
. В строке адреса вбей `smb://192.168.162.162/vagrant`.
. Имя пользователя `vagrant`, пароль `vagrant`.

Тебе должно быть видно содержимое директория пользователя `vagrant`, в том числе и `hw-01-твой_github_юзернейм`.

==== Linux

Используй любой smb-клиент для присоединения к папке `/vagrant`, расшареной на `192.168.162.162` c именем пользователя `vagrant` и паролем `vagrant`. Вероятно обозреватель файлов твоего дистрибутива поддерживает `smb` «из коробки» — обратись за инструкциями к документации.

== Инструменты для работы

Перед продвижением следует пробежаться по полезным инструментам, которые входят в набор любого хакера. Умение пользоаться некоторыми из них (например `git`, `make`) совершенно необходимо при выполнении заданий этого курса. Другие, например `gdb` или `tmux`, являются усилителями продуктивности. Первая из них помогает искать ошибки в коде, вторая позволяет использовать многозадачность более эффективно. Все описаные ниже инструменты уже находятся внутри ВМ и готовы к использованию.

NOTE: Этот документ не является исчерпывающим руководством по рассматриваемым инструментам. Вместо этого ниже будут преставлены ссылки на внешние ресурсы описывающие способ работы с тем или иным инструментом. Крайне рекомендуется ознакамливаться со всеми предлагаемыми материалами, даже если они не требуется для выполнения задания.

=== Git

`Git` — это средство контроля версий, которое помогает отлеживать изменения в коде. `GitHub` — это один из множества сервисов для размещения кода. Можно пользоваться `git` локально, но проталкивать (`git push`) изменения в `GitHub` для удобной совместной (с преподавателем) работы.

Возможно, что ты уже знаком с некоторыми коммандами `git`, однако понимание внуренних механизмов работы скрывающихся за относительно простыми командами позволит более глубоко понимать и предсказывать поведение этого инструмента.

Если ты никогда раньше не использовал `git` и хочешь разобраться «с самого начала», то начни (https://git-scm.com/book/ru/v2/Введение-О-системе-контроля-версий)[отсюда].

=== make

Программа `make` предназначена для автоматического создания исполняемых файлов и библиотек из исходного программного кода. Построение исполняемых файлов описывается с помощью правил, определенных в файле `Makefile`, который обычно располагается в корневом директории проекта, который требуется построить. Правила работают довольно интересно: в файле `Makefile` с помощью _особого синтаксиса_ описывается список зависимостей и `make` анализируя этот файл строит граф зависимостей для построения всего, что требуется. К сожалению _особый синтаксис_ довольно особый, временами он может сбивает с толку, особенно если ты плохо понимаешь, что в действительности делает `make`.

Документацию на русском можно найти (http://linux.yaroslavl.ru/docs/prog/gnu_make_3-79_russian_manual.html)[здесь], а практическое руководство с примерами (http://www.opennet.ru/docs/RUS/gnumake/)[тут]. Конечно же лучше всего читать официальную документацию на английском (https://www.gnu.org/software/make/manual/make.html)[тут].

Попробуй применить простейший способ использования `make` (без `Makefile`). Находясь в директории с заданием, можно скомпилировать и слинковать `wc.c` просто выполнив:
----
$ make wc
----

В результате будет создан исполнимый файл `wc`, который можно запустить. Попробуй:
----
$ ./wc wc.c
----

