= Лабораторная работа № 1: Исполняемые фалы

== Настройка
=== GitHub

Результаты домашних работ должны быть представлены на GitHub, для чего у тебя должена быть там учётка. Свой код надо хранить *строго* в приватных репозиториях.

=== Vagrant

Для выполнения заданий потребуется использовать готовый преконфигурированный Vagrant-образ виртуальной машины, который содержит все необходимые инструменты для запуска, тестирования и отладки кода. http://www.vagrantup.com/downloads.html[Vagrant] — это средство управления виртуальными машинами, он будет использоваться для загрузки и запуска подготовленного образа виртуальной машины.

[NOTE]
.*Только для пользователей Windows*
--
Поскольку Windows не поддерживает `ssh`, комманда `vagrant ssh`, которая потребуется вдальнейшем, приведет к ошибке. Vagrant предложит скачать Cygwin или что-то похожее, что поддерживает `ssh`. Cygwin — это набор программ (Linux комманд) для Windows. Тебе необходимо поставить Cygwin и использовать его терминал для выполнения команд. 

. Скачать с http://cygwin.com/install.html[сайта Cygwin] дистрибутив, подходящий к установленной версии Windows.
. Запустить скачаный файл (`setupx84_64.exe` или типа того).
. На экране приветствия нажать «Next».
. На экране «Choose A Download Source» выбрать «Install from Internet» и нажать «Next».
. На экране «Select Root Install Directory» нужно оставить предложенное значение для «Root Directory» и выбрать установку для всех пользователей «All Users». Нажать «Next».
. На экране «Select Local Package Directory» ничего не трогать. Нажать «Next».
. На экране «Select Your Internet Connection» оставить «Direct Connection». Нажать «Next».
. (Действие не требуется) Cygwin загрузит список доступных зеркал (то есть серверов на которых хранится программное обеспечение Cygwin).
. На экране «Choose A Download Site» нужно выбрать какой-нибудь сайт и нажать «Next».
. (Действие не требуется) Cygwin загрузит список доступного программного обеспечения.
. Теперь ты попал на экран «Select Packages». Нажми кнопку «View» в верхнем правом углу, чтобы было написано «Full» вместо «Category». Больше ничего не трогать.
. Для каждого перечисленного ниже пакета нажми на надпись «Skip», чтоб выбрать этот пакет для установки. При нажатии на «Skip» надпись должна превращаться в номер версии пакета, типа `2.1.4-1`. Возможно некоторые пакеты уже будут выбраны для установки, тогда нажимать ничего не надо.
.. bash: THE GNU Bourne Again SHell
.. git: Distributed version control system
.. git-completion: Bash completion for Git version control system
. Нажми «Next» для проверки списка установки.
. На экране «Resolving Dependencies» удостоверься, что выбран пункт «Select required packages» и нажми «Next».
. (Действие не требуется) Cygwin установит все выбранные пакеты.
. На экране «Create Icons» лучше выбрать оба пункта «Desktop icons» и «Start Menu icons», чтобы было легче отыскать «Cygwin Terminal». Нажми «Finish» для завершения.

Все последующие команды следует вводить в терминале «Cygwin Terminal».

--
. Vagrant зависит от VirtualBox (программное обеспечение с открытым программным кодом для виртуализации), поэтому прежде всего необходимо загрузить и установить свежую версию с https://www.virtualbox.org/wiki/Downloads[сайта VirtualBox].
. Установить свежую версию с http://www.vagrantup.com/downloads.html[сайта Vagrant].
. После установки Vagrant нужно ввести в терминал следующие комманды:
+
----
$ mkdir cs162-vm
$ cd cs162-vm
$ vagrant init cs162/spring2019
$ vagrant up
$ vagrant ssh
---- 
+
Эти команды приведут к тому, что произойдет загрузка подготовленного образа виртуальной машины, она будет запущена и будет поднято ssh-соединение с хоста в виртуальную машину. Отметим, что команда «up» требует для выполнения достаточно много времени и устойчивое соединение с интернетом.

. Все vagrant-команды требуется запускать из директория `cs162-vm`, который был создан ранее. *Нельзя удалять этот директорий*, иначе vagrant не будет знать как управлять виртуальной машиной (ВМ), которая была создана.
. Команда `vagrant halt` приведёт к остановке виртуальной машины. Для следующего запуска ВМ достаточно ввести только две комманды:
+
----
vagrant up
vagrant ssh
----

==== Решение проблем с Vagrant

Если комманда `vagrant up` выпадает с ошибкой, попробуй выполнить `vagrant provision` и проверить не исправит ли она ошибку. Если совсем всё плохо, можно попробовать полностью удалить ВМ командой `vagrant destroy`. Потом снова создать ВМ `vagrant up`.